// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyARQjSEirh5OY8cH0GwiHddryKNcpV7zMw',
    appId: '1:580995785797:web:37f2538cd4296e5b602f2c',
    messagingSenderId: '580995785797',
    projectId: 'savey-ecomers',
    authDomain: 'savey-ecomers.firebaseapp.com',
    storageBucket: 'savey-ecomers.appspot.com',
    measurementId: 'G-ZNN4ZW9FR6',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAj2gW_jG-zyYAdaHgQ6PYKycnOulnG2Rs',
    appId: '1:580995785797:android:095bda64c0c420ab602f2c',
    messagingSenderId: '580995785797',
    projectId: 'savey-ecomers',
    storageBucket: 'savey-ecomers.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCZegg8VeudVntjdmhw3wOn6OCD_t-PgX0',
    appId: '1:580995785797:ios:a60c926aa957b3ba602f2c',
    messagingSenderId: '580995785797',
    projectId: 'savey-ecomers',
    storageBucket: 'savey-ecomers.appspot.com',
    iosBundleId: 'com.example.saveyEconers',
  );
}
